---
name: AZE Iodine
version: 0.0.17
slug: iodine
description: >-
  IODINE
url: https://github.com/azenned/hassio-addons-directory/tree/main/iodine
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
boot: auto
host_network: true
privileged: 
  - NET_ADMIN 
map:
  - ssl:rw
devices:
  - /dev/net/tun:/dev/net/tun:c 200:10 rwm
options:
  nameserver: example.com
  topdomain: example.com
  password: PASSWORD
  fragsize: 1130
  namelen: 255
  dnsmode: TXT
  encode: base32 
  foreground: true
  ipv4: true
  ipv6: true
  skipraw: true
  tundevice: true
  forward: true
  networkdevice: wlan0
schema:
  nameserver: str
  topdomain: str
  password: str
  fragsize: int
  namelen: int
  dnsmode: str
  encode: list(base32|base64|base64u|base128)   
  foreground: bool
  ipv4: bool
  ipv6: bool
  skipraw: bool 
  tundevice: bool 
  forward: bool
  networkdevice: list(wlan0|eth0)   
  iptables: str?  
startup: services
full_access: true
