---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:5.2.2
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:5.2.2
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:5.2.2
  i386: ghcr.io/hassio-addons/ubuntu-base/i386:5.2.2
