---
  build_from:
    aarch64: ghcr.io/azenned/raspap-ubuntu-base/aarch64:9.0.0
    amd64: ghcr.io/azenned/raspap-base/amd64:9.0.0
    armv7: ghcr.io/azenned/raspap-base/armv7:9.0.0
    i386: ghcr.io/azenned/raspap-base/i386:9.0.0