---
name: AZE Hotspot wifi pour RPI
version: 0.0.1
slug: raspap
description: Addon Hotspot wifi with raspap-webgui
url: https://github.com/azenned/Hassio-addons/tree/master/raspap
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
startup: application
arch:
- armv7
map:
- config:rw
ports:
  80/tcp: 80
ports_description:
  80/tcp: Web interface
options:
 internet: true
schema:
 internet: "bool"
boot: manual
host_network: true
hassio_api: true
hassio_role: default
auth_api: true
full_access: true
options: {}
schema: {}
privileged:
- NET_ADMIN
stage: experimental
